mutation CreatePatient @auth(level: USER) {
  patient_insert(data: {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    dateOfBirth: "1990-01-01",
    createdAt_expr: "request.time",
    providerId_expr: "uuidV4()"
  })
}

query ListProviders @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  providers {
    id
    name
    specialty
    email
    phoneNumber
  }
}

mutation UpdateAppointmentNotes($id: UUID!, $notes: String) @auth(level: USER) {
  appointment_update(
    id: $id,
    data: {
      notes: $notes
    }
  )
}

query ListMedicalRecordsForPatient($patientId: UUID!) @auth(level: USER) {
  medicalRecords(where: {patientId: {eq: $patientId}}) {
    id
    diagnosis
    medications
    recordDate
    notes
  }
}